<?php
/**
 * Created by PhpStorm.
 * User: HP
 * Date: 2018/3/19
 * Time: 9:46
 */

namespace app\manages\controller;


use think\Controller;
use think\Session;

class Common extends Controller
{
    public function _initialize()
    {
//        parent::_initialize(); // TODO: Change the autogenerated stub
        if (!Session::get('name'))
        {
            $this->error('请先登录再操作哦~','manages/login/login');
        }
    }
}